"12星座該如何放下執著？｜2024/5/14直播" = "https://www.youtube.com/watch?v=zHLWShQXDBw"
"你不想遇到什麼星座的主管？#主管 #二選一 #處女座 #天秤座" = "https://www.youtube.com/watch?v=HlrykU3vKLs"
"5/13-5/19｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=PPUBbE2uE1Y"
"【唐陽雞酒屋】用視覺系保護自己的Eko、對未來很擔憂的Sandra ft. @amazingtalkershow" = "https://www.youtube.com/watch?v=fv-ZQJ3VhVw"
"【每月運勢】一定要勇敢改變的五月 #五月運勢" = "https://www.youtube.com/watch?v=JxWECcZb2TE"
"5/6-5/12｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=Y1EOlvxwzjc"
"唐綺陽直播｜可以勇敢改變的五月｜五月運勢" = "https://www.youtube.com/watch?v=czxDdJie9L4"
"週報又被分到累的？其實不用怕😌 #週報 #累 #占星" = "https://www.youtube.com/watch?v=GIFJmDte1ak"
"你是改寫命運的導演 #運勢 #占星 #命運" = "https://www.youtube.com/watch?v=whIvMnfrNJA"
"天註定？不一定 #運勢 #占星 #命運" = "https://www.youtube.com/watch?v=whIvMnfrNJA"
"4/29-5/5｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=_DNUMeWCfL0"
"【唐陽雞酒屋】向宇宙下訂單的體質 ft.蔡健雅" = "https://www.youtube.com/watch?v=xHKPx_X1iHA"
"社恐I人，會社交，但電池量過低🪫🤪#MBTI #16型人格 #占星" = "https://www.youtube.com/watch?v=t11V843V0AM"
"4/22-4/28｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=lPlao1RviPg"
"【唐陽雞酒屋】道理我都懂，啊又做不到ft.周慕姿" = "https://www.youtube.com/watch?v=zUkg9KHf6s0"
"你心目中最難追的星座是…？ #唐綺陽xVogue #星座#難追 #感情" = "https://www.youtube.com/watch?v=JBOKFF5yIys"
"最難追星座男，好好先生都上榜了🤪" = "https://www.youtube.com/watch?v=PDOiko3-r-s"
"4/15-4/21｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=kLJ3JlJd6e8"
"焦慮代表你靈魂挺有野心的🎧EP310 #30歲 #長大 #壓力 #焦慮" = "https://www.youtube.com/watch?v=zGV8Hj9dAUs"
"【土象星座篇】水逆的四月 #四月運勢" = "https://www.youtube.com/watch?v=f717QkjXXIA"
"【水象星座篇】水逆的四月 #四月運勢" = "https://www.youtube.com/watch?v=qII9DG2DbvE"
"【火象星座篇】水逆的四月 #四月運勢" = "https://www.youtube.com/watch?v=sY-QYdWsBhI"
"【風象星座篇】水逆的四月 #四月運勢" = "https://www.youtube.com/watch?v=Koo29lNKJfI"
"4/8-4/14｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=rZ_5Ry9I5_Q"
"今早6點正式水逆啦！#占星 #水逆 #星座" = "https://www.youtube.com/watch?v=tb0z8SmIF4I"
"4/1-4/7｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=mt3dI2Vn0jc"
"唐綺陽直播｜水逆的四月｜四月運勢" = "https://www.youtube.com/watch?v=3KK35ERenDo"
"各位小心肝，請小心肝。" = "https://www.youtube.com/watch?v=FDnZAK4krqM"
"【唐陽雞酒屋】感情不順都是肝的問題？ft.簡少年" = "https://www.youtube.com/watch?v=WzBnD_AOmJI"
"3/25-3/31｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=1AogaG82Jx4"
"3/18-3/24｜星座運勢週報｜唐綺陽" = "https://www.youtube.com/watch?v=sMCsPzWum8I"
"12星座想哭的時候💦 #唐綺陽xVogue" = "https://www.youtube.com/watch?v=q0uPtN9787o"
"什麼！魔羯座也會哭？12星座，想哭的時候" = "https://www.youtube.com/watch?v=d5Oy-1Qono4"
