"rss" = "https://feeds.buzzsprout.com/1974862.rss"
"apple" = "https://podcasts.apple.com/tw/podcast/%E7%99%BE%E9%9D%88%E6%9E%9C-news/id1106847606"
"google" = "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zb3VuZGNsb3VkLmNvbS91c2Vycy9zb3VuZGNsb3VkOnVzZXJzOjIyMTM2MTk4MC9zb3VuZHMucnNz"
"spotify" = "https://api.spotify.com/v1/shows/5Vv32KtHB3peVZ8TeacUty/episodes?market=TW&limit=50"
"youtube" = "https://www.youtube.com/feeds/videos.xml?channel_id=UCD2KoUc0f4Bv2Bz0mbOah8g"

[correct]
"\u200b" = ""
"å•¦â€â™‚ï¸ã€" = "å•¦ğŸ™…â€â™‚ï¸ã€"
"Russia\"" = "Russiaâ€"
"æ—…æ¸¸" = "æ—…éŠ"
"ä¸€å‘¨" = "ä¸€é€±"
"è®€æ›¸æœƒ å‚€å„¡èŠ±ï¼š" = "è®€æ›¸æœƒï¼šå‚€å„¡èŠ± "
# https://ronjabook.blogspot.com/2012/03/blog-post_25.html
"ç¹å¢ƒ" = "é¶å¢ƒ"
"è“‹äºç´" = "è“‹äºé‚£"
" - 0" = " - #"
"The KK Show - #90 è‘‰è€€å…ƒæ•™æˆ" = "The KK Show - #91 è‘‰è€€å…ƒæ•™æˆ"
"å¿ƒç†å’¨å•†" = "å¿ƒç†è«®å•†"
"è·èŠ±é‚Š" = "è·è‘‰é‚Š"
"5ï¼Œ6" = "5ã€6"
"é†«è­·äººå“¡We Love Youã€" = "é†«è­·äººå“¡We Love Youï¼"
"èˆ‡åœ¨ä¸­åœ‹å°åŸçš„è½çœ¾èŠå¤©" = "æ­¡è¿è¢«å°åŸçš„è½çœ¾ä¾†èŠå¤©"
